src/Entity/Artist.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ArtistRepository")
 */
class Artist implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Link", mappedBy="artist", cascade={"all"})
     * @Assert\Valid()
     */
    private $videoLinks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="artist", cascade={"all"})
     * @Assert\Valid()
     */
    private $photos;

    /**
     *
     * @Assert\Length(min="3", max="50")
     * @Assert\NotBlank(
     *     message="The name is required")
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stage_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $biography;

    /**
     * @ORM\Column(type="boolean")
     */
    private $approved;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @Assert\NotBlank
     * @Assert\Email()
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $number;

    public function __construct()
    {
        $this->videoLinks = new ArrayCollection();
        $this->photos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId($id): ?int
    {
        return $this->id = $id;
    }
    

    /**
     * @return Collection|Link[]
     */
    public function getVideoLinks(): Collection
    {
        return $this->videoLinks;
    }

    public function addVideoLink(Link $videoLink): self
    {
        if (!$this->videoLinks->contains($videoLink)) {
            $this->videoLinks[] = $videoLink;
            $videoLink->setArtist($this);
        }

        return $this;
    }

    public function removeVideoLink(Link $videoLink): self
    {
        if ($this->videoLinks->contains($videoLink)) {
            $this->videoLinks->removeElement($videoLink);
            // set the owning side to null (unless already changed)
            if ($videoLink->getArtist() === $this) {
                $videoLink->setArtist(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setArtist($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getArtist() === $this) {
                $photo->setArtist(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getStageName(): ?string
    {
        return $this->stage_name;
    }

    public function setStageName(string $stage_name): self
    {
        $this->stage_name = $stage_name;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }

    public function getApproved(): ?bool
    {
        return $this->approved;
    }

    public function setApproved(bool $approved): self
    {
        $this->approved = $approved;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Specify data which should be serialized to JSON
     * @link https://php.net/manual/en/jsonserializable.jsonserialize.php
     * @return mixed data which can be serialized by <b>json_encode</b>,
     * which is a value of any type other than a resource.
     * @since 5.4.0
     */
    public function jsonSerialize()
    {
        return [
            'id' => $this->getId(),
            'email' => $this->getEmail(),
            'number' => $this->getNumber(),
            'photos' => $this->getPhotos(),
            'videoLinks' => $this->getVideoLinks(),
            'biography' => $this->getBiography(),
            'name' => $this->getName(),
            'country' => $this->getCountry(),
            'stage_name' => $this->getStageName(),
            'approved' => $this->getApproved(),
            'type' => $this->getType()
        ];
    }
}

templates/AdminController/_delete_form.html.twig
<form method="post" action="{{ path('artist_delete', {'id': artist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this artist');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artist.id) }}">
    <button class="btn btn-danger editPage showPageButton">Delete</button>
</form>

templates/AdminController/_form.html.twig
{% form_theme form 'jquery.collection.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form.name,{'attr':{'class':'form-control'}}) }}
    {{ form_errors(form.name) }}

    {{ form_row(form.country,{'attr':{'class':'form-control'}} )}}
    {{ form_row(form.stage_name,{'attr':{'class':'form-control'}} )}}
    {{ form_row(form.email,{'attr':{'class':'form-control'}} )}}
    {{ form_row(form.number,{'attr':{'class':'form-control'}} )}}

    {{ form_row(form.biography,{'attr':{'class':'col-md-12','rows':8}} )}}
    <span class="switcher artist1_approved">
        {{ form_row(form.approved)}}
    </span>
    {{ form_row(form.type,{'attr':{'class':'form-control'}})}}
    <h2>Fotos:</h2>
    <div>
        <label for="artist1_files" class="btn btn-primary w-25">Upload</label>
        {{ form_widget(form.files,{'attr':{'id':'image_uploads','name':'image_uploads'}}) }}
    </div>
    <div class ="preview">
        <p></p>
    </div>
    <div class="d-flex flex-wrap flex-row justify-content-around mt-4">
        {% if artist.photos |length < 1%}
            <h1>No Fotos</h1>
        {% endif %}
        {% for foto in artist.photos %}
            <div class="pictureAdmin">
            <a href="{{ path('fotoDelete') }}" class="foto-delete" id="{{ foto.id }}">
                <img class="d-block" src="{{ asset('uploads/fotos/'~foto.path) }}" alt="Foto">
            </a>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex" >
        <div class="w-100 mt-5">
            {{ form_row(form.videoLinks,{'label':'Video Links:'})}}
        </div>
    </div>
    <button class="btn btn-warning editPage mt-5">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/AdminController/edit.html.twig
{% extends 'AdminController/index.html.twig' %}

{% block title %}Edit Artist{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/admin.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/checkbox.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div class="container">
    <h3>Edit Artist</h3>

    {{ include('AdminController/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('AdminController/_delete_form.html.twig') }}

    <a href="{{ path('artist_index') }}" class="btn btn-info editPage">Back to list</a>

    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/fotosAdmin.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/adminFotoDelete.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/jquery.collection.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        $('.my-selector').collection();
    </script>

{% endblock %}

templates/AdminController/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist index{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/admin.css') }}" rel="stylesheet" />
{% endblock %}
{% block header %}
    <div class="container">
        <div class="d-flex flex-row flex-wrap justify-content-between mb-5">
            <div>
             <img src="{{ asset('images/Logo.jpeg') }}" class="img-fluid rounded logo-0" width="250" height="250">
                <div class="d-flex justify-content-center w-100">
                    <a class="btn btn-primary w-75" href="{{ path('artist_index') }}"><h2>Home</h2></a>
                </div>
            </div>
            </div>
    </div>
        {% endblock %}
{% block body %}
    <div class="container">
    <h3>Artist index</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Country</th>
                <th>Stage Name</th>
                <th>Approved</th>
                <th>Type</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td>{{ artist.id }}</td>
                <td>{{ artist.name }}</td>
                <td>{{ artist.country }}</td>
                <td>{{ artist.stageName }}</td>
                <td>{{ artist.approved ? 'Yes' : 'No' }}</td>
                <td>{{ artist.type }}</td>
                <td>
                    <a href="{{ path('artist_show', {'id': artist.id}) }}" class="btn btn-primary indexPage">Show</a>
                    <a href="{{ path('artist_edit', {'id': artist.id}) }}" class="btn btn-success indexPage">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('add_artist')}}" class="btn btn-danger">Create New</a>
        <div class="navigation mt-5 d-flex justify-content-center">
            {{ knp_pagination_render(artists) }}
        </div>
    </div>
{% endblock %}

templates/AdminController/show.html.twig
{% extends 'AdminController/index.html.twig' %}

{% block title %}Artist{% endblock %}
{% block stylesheets %}
{{ parent() }}
    <link href="{{ asset('css/admin.css') }}" rel="stylesheet" />
{% endblock %}

{% block body %}
    <div class="container">
    <h3>Artist</h3>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artist.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ artist.name }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ artist.number }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ artist.country }}</td>
            </tr>
            <tr>
                <th>Stage Name</th>
                <td>{{ artist.stageName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ artist.email }}</td>
            </tr>
            <tr>
                <th>Biography</th>
                <td>{{ artist.biography|nl2br}}</td>
            </tr>
            <tr>
                <th>Approved</th>
                <td>{{ artist.approved ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ artist.type }}</td>
            </tr>


        </tbody>
    </table>

        <h1>Fotos:</h1>
        <div class="d-flex flex-wrap flex-row justify-content-around">
            {% if artist.photos |length < 1%}
                <h1>No Fotos</h1>
            {% endif %}
        {% for foto in artist.photos %}
            <div class="pictureAdmin">
           <img class="d-block" src="{{ asset('uploads/fotos/'~foto.path) }}" alt="Foto">
            </div>
        {% endfor %}
        </div>

        <h1>Videos:</h1>
        <div class="d-flex flex-wrap flex-row justify-content-around m-5">
            {% for video in links %}
                <iframe class="d-block m-4 videos" src="{{video}}" width="400px" height="400px" style="border: 1px solid white"></iframe>
            {% endfor %}
        </div>

        <div class='showPage'>
    <a href="{{ path('artist_index') }}" class="btn btn-info showPageButton">Back to list</a>
    <a href="{{ path('artist_edit', {'id': artist.id}) }}" class="btn btn-warning showPageButton">Edit</a>
    {{ include('AdminController/_delete_form.html.twig') }}
        </div>
    </div>

{% endblock %}